{% set name = "grass" %}
{% set version = "8.4.1" %}
{% set sha256 = "611e82dd919cd0e5c1a511e7efbc5c769e22ac6c613c3c4a2633c5d4b07c7e31" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/OSGeo/grass/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # Windows not yet implemented
  script: bld.bat

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - gdal
    - geos
    - proj
    - proj-data
    - sqlite
    - cairo
    - freetype
    - fontconfig
    - libpng
    - libjpeg-turbo
    - libtiff
    - zlib
    - zstd
    - bzip2
    - fftw
    - liblapack
    - libnetcdf
    - pdal
  run:
    - python
    - gdal
    - libgdal-core
    - geos
    - proj
    - proj-data
    - sqlite
    - cairo
    - freetype
    - fontconfig
    - libpng
    - libjpeg-turbo
    - libtiff
    - zlib
    - zstd
    - bzip2
    - fftw
    - liblapack
    - libnetcdf
    - pdal
    - libpdal-core
    # Python modules typically used by GRASS python tools
    - numpy
    - pillow
    - matplotlib-base
    - python-dateutil

test:
  commands:
    - grass --version
    - grass --tmp-project EPSG:4326 --exec g.version -rge

about:
  home: https://grass.osgeo.org/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: GRASS computational engine for raster, vector, and geospatial processing. 
  description: |
    GRASS is a geospatial engine that enables spatial data analysis,
    visualization, and modeling. It provides researchers and practitioners
    with science-backed tools to understand and manage landscapes,
    natural resources, and human environments.
  dev_url: https://github.com/OSGeo/grass
  doc_url: https://grass.osgeo.org/grass-stable/manuals/

extra:
  recipe-maintainers:
    - HuidaeCho
    - dudaka
    - wenzeslaus
